apiVersion: v1
appVersion: "1.0"
description: A Helm chart for a Kubernetes job running distributed TensorFlow model training using the TFJob Operator with a master, parameter server, and workers.
name: tf-distributed
version: 0.1.0
