# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

masterCount: 1
psCount: 1
workerCount: 1

image:
  pullPolicy: IfNotPresent

service:
  type: TFJob

ingress:
  enabled: false
